<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return [
    'Prophecy\\' => [$vendorDir.'/phpspec/prophecy/src'],
    'PHPExcel' => [$vendorDir.'/phpoffice/phpexcel/Classes'],
    'Mockery' => [$vendorDir.'/mockery/mockery/library'],
    'Mcamara\\LaravelLocalization' => [$vendorDir.'/mcamara/laravel-localization/src'],
    'Maatwebsite\\Excel\\' => [$vendorDir.'/maatwebsite/excel/src'],
    'JakubOnderka\\PhpConsoleHighlighter' => [$vendorDir.'/jakub-onderka/php-console-highlighter/src'],
    'JakubOnderka\\PhpConsoleColor' => [$vendorDir.'/jakub-onderka/php-console-color/src'],
    'HTMLPurifier' => [$vendorDir.'/ezyang/htmlpurifier/library'],
    'Doctrine\\DBAL\\' => [$vendorDir.'/doctrine/dbal/lib'],
    'Doctrine\\Common\\Lexer\\' => [$vendorDir.'/doctrine/lexer/lib'],
    'Doctrine\\Common\\Inflector\\' => [$vendorDir.'/doctrine/inflector/lib'],
    'Doctrine\\Common\\Collections\\' => [$vendorDir.'/doctrine/collections/lib'],
];
